--  This file is automatically generated by Makefile

package Version is
   Ghdl_Ver     : constant String :=
     "7.0.0-dev";

   Ghdl_Ref     : constant String :=
     "unknown";

   Ghdl_Hash    : constant String :=
     "unknown";

   Ghdl_Release : constant String :=
     "(tarball)" &
     " [Dunoon edition]";
end Version;
